### PR TITLE
Improved Shower Cheating

### PR DESCRIPTION
**Pull request by etyley**
Recently ran a bug was found where the shower track finder cheating tool did not work for photons. This is now fixed in this PR, and should work for both rolled-up and non rolled-up showers.
I also added some additional warnings/info messages to help debug this sort of issue in the future.
I also gave the cheating tools a bit of a tidy up, including moving some code that was shared between different tools into an alg.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
argoneutcode CI tests are fine: https://dbweb8.fnal.gov:8443/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/5871&builds=

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
