### PR TITLE
More switches from TVector3 to Point_t and Vector_t

### PR DESCRIPTION
**Pull request by knoepfel**
Addresses https://cdcvs.fnal.gov/redmine/issues/27737

### CODE REVIEW

**Comment by knoepfel** [comment]
@henrylay97, I'd appreciate it if you could look over these changes.  I've switched all of the position/direction vectors to `geo::Point_t/geo::Vector_t`, but I've left all of the `*Err` vectors as `TVector3`...but probably those should be converted, too?    In addition, I removed some unnecessary conversions from `geo::Point_t/geo::Vector_t` to `TVector3`, and vice versa.

Please let me know if you see anything alarming.

**Comment by etyley** [comment]
Hi Kyle, I also started looking at making a more wholesale change from `TVector3` but you beat me to making the PR (my branch is here: https://github.com/etyley/larpandora/tree/feature/etyley_TVector3). I had a look through your changes and they all look good to me. I definitely agree that changing the errors over would simplify things and is probably worth doing.

**Comment by henrylay97** [comment]
Hi both! Yeah these changes all look sensible to me. I will run them through a few checks offline as the CI is still taking time to get back on its feet. I also see no reason why we shouldn't migrate the errors too :)

**Comment by knoepfel** [comment]
Thanks, @etyley and @henrylay97.  I just pushed changes converting the errors to use `geo::Point_t` and `geo::Vector_t`.  Yeah, it looks like I duplicated some of your efforts, Ed.  Sorry about that.

**Comment by lgarren** [comment]
trigger build

**Comment by henrylay97** [comment]
Offline, my tests ran fine (admittedly only testing the SBND specific combination/configuration of these tools). I'm satisfied that they work / don't break anything at our end.

**Comment by lgarren** [comment]
@henrylay97 were you able to check everything offline?  Are there any issues?

Nevermind, I just saw your comment.  Thanks!

**Comment by lgarren** [comment]
approve

**Pull request merged**
