### PR TITLE
Make detector clocks/properties thread-safe

### PR DESCRIPTION
**Pull request by knoepfel**

### CODE REVIEW

**Comment by johnmarshall80** [comment]
Hi, are the formatting changes mandatory here (I note that they are, helpfully, in a separate commit)? We've a pretty much consistent style across the Pandora code base, which is roughly defined in a .clang-format file as follows:

```BasedOnStyle: LLVM  
BreakBeforeBraces: Allman  
ColumnLimit: 140  
PenaltyExcessCharacter: 1  
IndentWidth: 4  
AccessModifierOffset: -4  
ConstructorInitializerAllOnOneLineOrOnePerLine: true  
BreakConstructorInitializers: AfterColon  
AllowShortFunctionsOnASingleLine: false  
IndentCaseLabels: true  
AlignAfterOpenBracket: DontAlign  
AlignConsecutiveAssignments: true  
```

We're not so wedded to the choice of style/formatting for larpandora (although definitely interested in your thoughts), which only does input/output for Pandora algorithm flow, but would definitely appreciate a proper discussion in advance before any application to larpandoracontent.

Many thanks!

**Comment by knoepfel** [comment]
@johnmarshall80, thanks for the comment.  When I've discussed these changes in past LArSoft coordination meetings (most recently on May 19), I've explicitly mentioned that I will be applying clang-format to the files that require changes.  The reason is that because there are so many files that must be changed across all LArSoft repositories, it was better to homogenize their layout in a separate commit before making meaningful adjustments.  No objections were voiced at each of the meetings.

That said, if you have a clang-format file you'd like me to use for `larpandora`, I have no objection.  It would be helpful if you could send me one instead of me having to put one together myself.

Also, please note that I will not be touching `larpandoracontent` at all--my understanding is that is pretty much your package to handle.

**Comment by johnmarshall80** [comment]
Hi @knoepfel, thanks very much for the helpful reply. I'm obviously trying to speak on behalf of all of the Pandora developers here (we do try to make sure we have at least a few present in all  coordination meetings!): I think that we're happy to do whatever we can to follow all of the LArSoft team's recommended best practices for larpandora (which is a fully-fledged LArSoft package), but we do also appreciate that little bit of extra autonomy for larpandoracontent (which doesn't depend on any other LArSoft packages, other than externals). Hopefully that works for you too, in which case happy to wave this PR through, and always happy to discuss further in future too. Thanks.

**Comment by knoepfel** [comment]
Yes, @johnmarshall80, the division of responsibilities between `larpandora` and `larpandoracontent`  has worked well, and it should continue!  My apologies if I caused undue alarm.

**Pull request closed without merging**
