### PR TITLE
PandoraShower Bugfixes

### PR DESCRIPTION
**Pull request by etyley**
This PR consists of 3 separate bugfixes in PandoraModularShowerCreation:

BayesianTruncationdEdx: 
- Fix mismatched fcl parameter names (Fixes #8)
- Removed reference to SBND specific prior file that was giving an error for not being found in ICARUS. 

TrajPointdEdx:
- Fix issue with initialisation of max_hits when calculating the best plane which lead to planes with 0 hits being taken as the best plane. Now require at least one plane to have at least one hit or return an error, the previously intended behaviour hopefully implemented correctly now
- Added additional debug output for ease of future debugging

NumElectronsEnergy:
- Switch from using views to planes to make it work in ICARUS
- Refactored to more closely mirror the LinearEnergy tool
- ShowerEnergOutputLabel is now a fcl param rather than hard-coded
- NumElectrons tool now calculates a best plane in the same way as the Linear energy tool (plane with the most hits) 

This has been tested in SBND (myself), DUNE (@absolution1) and ICARUS (@brucehoward-physics) and no changes to output are expected with default configurations.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
trigger build

**Comment by knoepfel** [comment]
Changes look good--thanks Ed.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
approve

**Pull request merged**
