### PR TITLE
Pandora deep learning infrastructure

### PR DESCRIPTION
**Pull request by AndyChappell**
This pull request introduces the infrastructure to support deep learning via LibTorch. There will be a talk on this and the associated larpandoracontent pull request (LArSoft/larpandoracontent/pull/13) upon which it depends, in the LArSoft Coordination meeting on 20 October.

This update allows LArPandoraInterface to link against the new deep learning-aware library in larpandoracontent.

CI testing was undertaken, please see dune_ci/10372, which completed successfully.

Please feel free to contact me with any queries, or alternatively I'll be happy to address them in the LArSoft Coordination meeting.

### CODE REVIEW

**Comment by absolution1** [comment]
Just so everyone is on the same page:  
This PR relies on https://github.com/LArSoft/larpandoracontent/pull/13 but https://github.com/LArSoft/larpandoracontent/pull/13 is waiting on a `product_deps` update from SciSoft.

**Comment by AndyChappell** [comment]
I've pushed updates to handle the presence/absence of LibTorch during the build ahead of any additional discussion in today's LArSoft Coordination Meeting.

**Comment by lgarren** [comment]
trigger build LArSoft/larpandora#13  LArSoft/larpandoracontent#13

**Comment by gartung** [comment]
trigger build with pull requests #13, larsoft/larpandoracontent#13

**Comment by lgarren** [comment]
approve

**Pull request merged**
