### PR TITLE
A new detector interface

### PR DESCRIPTION
**Pull request by absolution1**
Hi everyone,

This PR includes a new detector interface to handle mapping semi-specific detector details to the pandora input.

The change centres around an empty interface class with a few concrete derived interfaces, one per LArTPC type.
This change is necessary to incorporate the vertical drift detector into the pandora workflow as the old interface was reaching its capacity.

It also has a nice knockoff effect of reducing the amount of code in LArPandoraGeometry and LArPandoraInput.

Testing has been done to check that pandora's current LArTPC consumers are unaffected; we're not anticipating any change in output for any detector.  Hopefully the CI will confirm this.

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
Lesson learnt, don't be too over zealous with clang formatting.  Let's try this again.

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
trigger build

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
